version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
  logstash:
    image: logstash
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
networks:
  web_nw:
    driver: bridge

