version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch-container
    hostname: elasticsearch-server
    networks:
      - web_nw
    expose:
      - "9200"
      - "9300"
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
  logstash:
    image: logstash
    hostname: logstash-server
    container_name: logstash-container
    volumes:
      - $PWD:/config-dir
    command: logstash -f /config-dir/logstash.conf
    networks:
      - web_nw
    expose:
      - "5959"
    ports:
      - "5959:5959"
    restart: always
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    container_name: kibana-container
    hostname: kibana-server
    depends_on:
      - elasticsearch
      - logstash
    networks:
      - web_nw
    expose:
      - "5601"
    ports:
      - "5601:5601"
    restart: always
networks:
  web_nw:
    driver: bridge

